// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCNjvllrMIIy_eNWTJqfWXof3neeu4A7I',
    appId: '1:251855909245:web:53d41bf801a046ed751c14',
    messagingSenderId: '251855909245',
    projectId: 'foodolist',
    authDomain: 'foodolist.firebaseapp.com',
    storageBucket: 'foodolist.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmD9EGHlDfIPic0ifmdsXVaKaTp7uSE9s',
    appId: '1:251855909245:android:fe9352a51116de65751c14',
    messagingSenderId: '251855909245',
    projectId: 'foodolist',
    storageBucket: 'foodolist.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB94owkDDyUi2Ifgnmo4C3SDNxKI6T9zyk',
    appId: '1:251855909245:ios:bfbc8a2f4b10df76751c14',
    messagingSenderId: '251855909245',
    projectId: 'foodolist',
    storageBucket: 'foodolist.appspot.com',
    iosClientId: '251855909245-sqm4osf2rqelj9r3fbcb5ujapvrhu9bg.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB94owkDDyUi2Ifgnmo4C3SDNxKI6T9zyk',
    appId: '1:251855909245:ios:bfbc8a2f4b10df76751c14',
    messagingSenderId: '251855909245',
    projectId: 'foodolist',
    storageBucket: 'foodolist.appspot.com',
    iosClientId: '251855909245-sqm4osf2rqelj9r3fbcb5ujapvrhu9bg.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodolist',
  );
}
